name: Pull-Request

on:
  pull_request:
    branches:
      - main

env:
  CMAKE_ARGS: "-DCMAKE_CXX_COMPILER=/usr/bin/g++-9 -DCMAKE_C_COMPILER=/usr/bin/gcc-9"

jobs:

  call:
    uses: openfheorg/openfhe-development/.github/workflows/reuseable_workflow.yml@github-ci
    with:
      mb2_debug: true
      mb2_tcm: true
      mb4_noflag: true
      mb4_debug: true
      mb4_tcm: true
      mb6_ntl_noflag: true
      mb6_ntl_debug_tcm: true
      mb6_ntl_tcm: true
