name: Reuseable Workflow

on:
  workflow_call:
    inputs:
      cmake_args:
        description: 'Custom cmake arguments'
        type: string
        required: false
        default: ''
      mb2_debug:
        description: 'Run mb2_debug'
        type: boolean
        required: false
        default: false
      mb2_tcm:
        description: 'Run mb2_tcm'
        type: boolean
        required: false
        default: false
      mb4_noflag:
        description: 'Run mb4_noflag'
        type: boolean
        required: false
        default: false
      mb4_debug:
        description: 'Run mb4_debug'
        type: boolean
        required: false
        default: false
      mb4_tcm:
        description: 'Run mb4_tcm'
        type: boolean
        required: false
        default: false
      mb6_ntl_noflag:
        description: 'Run mb6_ntl_noflag'
        type: boolean
        required: false
        default: false
      mb6_ntl_debug_tcm:
        description: 'Run mb6_ntl_debug_tcm'
        type: boolean
        required: false
        default: false
      mb6_ntl_tcm:
        description: 'Run mb6_ntl_tcm'
        type: boolean
        required: false
        default: false

jobs:

  ###############################################
  #
  #    default jobs starts here
  #
  ###############################################
  default:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: default
      uses: openfheorg/openfhe-development/.github/actions/default_builder@github-ci
      with:
        module_name: default


  ###############################################
  #
  #    mb2_tcm jobs starts here
  #
  ###############################################
  mb2_tcm:
    needs: [default, mb4_noflag, mb6_ntl_noflag]
    runs-on: [self-hosted, Linux, X64]
    if: inputs.mb2_tcm
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: mb2_tcm
      uses: openfheorg/openfhe-development/.github/actions/default_builder@github-ci
      with:
        module_name: mb2_tcm
        mathbackend: 2
        with_tcm: true
        run_extras: true


  ###############################################
  #
  #    mb2_debug jobs starts here
  #
  ###############################################
  mb2_debug:
    needs: [default, mb4_noflag, mb6_ntl_noflag]
    runs-on: [self-hosted, Linux, X64]
    if: inputs.mb2_debug
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: mb2_debug
      uses: openfheorg/openfhe-development/.github/actions/default_builder@github-ci
      with:
        module_name: mb2_debug
        mathbackend: 2
        with_debug: true
        run_extras: true


  ###############################################
  #
  #    mb4_noflag jobs starts here
  #
  ###############################################
  mb4_noflag:
    needs: default
    runs-on: [self-hosted, Linux, X64]
    if: inputs.mb4_noflag
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: mb4_noflag
      uses: openfheorg/openfhe-development/.github/actions/default_builder@github-ci
      with:
        module_name: mb4_noflag
        mathbackend: 4
        run_extras: true


  ###############################################
  #
  #    mb4_tcm jobs starts here
  #
  ###############################################
  mb4_tcm:
    needs: [default, mb4_noflag, mb6_ntl_noflag]
    runs-on: [self-hosted, Linux, X64]
    if: inputs.mb4_tcm
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: mb4_tcm
      uses: openfheorg/openfhe-development/.github/actions/default_builder@github-ci
      with:
        module_name: mb4_tcm
        mathbackend: 4
        with_tcm: true
        run_extras: true


  ###############################################
  #
  #    mb4_debug jobs starts here
  #
  ###############################################
  mb4_debug:
    needs: [default, mb4_noflag, mb6_ntl_noflag]
    runs-on: [self-hosted, Linux, X64]
    if: inputs.mb4_debug
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: mb4_debug
      uses: openfheorg/openfhe-development/.github/actions/default_builder@github-ci
      with:
        module_name: mb4_debug
        mathbackend: 4
        with_debug: true
        run_extras: true


  ###############################################
  #
  #    mb6_ntl_noflag jobs starts here
  #
  ###############################################
  mb6_ntl_noflag:
    needs: default
    runs-on: [self-hosted, Linux, X64]
    if: inputs.mb6_ntl_noflag
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: mb6_ntl_noflag
      uses: openfheorg/openfhe-development/.github/actions/default_builder@github-ci
      with:
        module_name: mb6_ntl_noflag
        mathbackend: 6
        run_extras: true


  ###############################################
  #
  #    mb6_ntl_tcm jobs starts here
  #
  ###############################################
  mb6_ntl_tcm:
    needs: [default, mb4_noflag, mb6_ntl_noflag]
    runs-on: [self-hosted, Linux, X64]
    if: inputs.mb6_ntl_tcm
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: mb6_ntl_tcm
      uses: openfheorg/openfhe-development/.github/actions/default_builder@github-ci
      with:
        module_name: mb6_ntl_tcm
        mathbackend: 6
        with_tcm: true
        run_extras: true


  ###############################################
  #
  #    mb6_ntl_debug_tcm jobs starts here
  #
  ###############################################
  mb6_ntl_debug_tcm:
    needs: [default, mb4_noflag, mb6_ntl_noflag]
    runs-on: [self-hosted, Linux, X64]
    if: inputs.mb6_ntl_debug_tcm
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: mb6_ntl_debug_tcm
      uses: openfheorg/openfhe-development/.github/actions/default_builder@github-ci
      with:
        module_name: mb6_ntl_debug_tcm
        mathbackend: 6
        with_debug: true
        with_tcm: true
        run_extras: true

  ###############################################
  #
  #    mb2_natopt jobs starts here
  #
  ###############################################
  mb2_natopt:
    needs: [default, mb2_debug, mb2_tcm, mb4_noflag, mb4_debug, mb4_tcm, mb6_ntl_noflag, mb6_ntl_debug_tcm, mb6_ntl_tcm]
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: mb2_natopt
      uses: openfheorg/openfhe-development/.github/actions/default_builder@github-ci
      with:
        module_name: mb2_natopt
        mathbackend: 2
        with_debug: false
        with_nativeopts: true
        with_tcm: false
        run_extras: false
        run_benchmark: true
